# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullaniciadi', models.CharField(max_length=20)),
                ('cevap', models.CharField(max_length=200)),
                ('sorunumarasi', models.IntegerField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('cevapresmi', models.FileField(blank=True, null=True, upload_to='')),
                ('isim', models.CharField(blank=True, max_length=50)),
                ('soyisim', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10)),
                ('soyisim', models.CharField(max_length=15)),
                ('baslik', models.CharField(max_length=100)),
                ('duyuru', models.TextField(null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('duyuru_sinif', models.CharField(max_length=50, null=True)),
                ('resim', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='kullanicilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('soyisim', models.CharField(max_length=20)),
                ('kullaniciadi', models.CharField(max_length=20)),
                ('parola', models.CharField(max_length=20)),
                ('okul', models.CharField(max_length=50)),
                ('sinif', models.CharField(max_length=100, null=True)),
                ('numara', models.CharField(max_length=1000, null=True)),
                ('kullanici_mail', models.EmailField(max_length=254, unique=True)),
                ('soru_sayisi', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-soru_sayisi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='mail_parola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.CharField(max_length=50)),
                ('parola', models.IntegerField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='puanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puanidsi', models.IntegerField()),
                ('puan', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorupuan', models.CharField(blank=True, max_length=100)),
                ('kullanici_adi', models.CharField(blank=True, max_length=50)),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.CharField(max_length=5000)),
                ('ders', models.CharField(max_length=100)),
                ('kitap', models.CharField(blank=True, max_length=100)),
                ('sayfano', models.CharField(blank=True, max_length=100)),
                ('soruno', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('isim', models.CharField(blank=True, max_length=50)),
                ('soyisim', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
